
import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
    // CORS 헤더 설정
    const allowedOrigins = [
        process.env.NODE_ENV === 'development' ? 'http://localhost:5173' : null,
        process.env.PRODUCTION_URL || (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : null)
    ].filter(Boolean) as string[];

    const origin = req.headers.origin;
    if (origin && allowedOrigins.includes(origin)) {
        res.setHeader('Access-Control-Allow-Origin', origin);
    }

    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With, Accept, Origin');
    res.setHeader('Access-Control-Max-Age', '86400');

    if (req.method === 'OPTIONS') {
        return res.status(200).json({ message: 'CORS preflight successful' });
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { question, caption, createdAt, filename, dropboxUrl, autoGenerated } = req.body;

        if (!process.env.AIRTABLE_API_TOKEN || !process.env.AIRTABLE_BASE_ID || !process.env.AIRTABLE_TABLE_ID) {
            throw new Error('필수 환경변수가 설정되지 않았습니다: AIRTABLE_API_TOKEN, AIRTABLE_BASE_ID, AIRTABLE_TABLE_ID');
        }

        const recordData = {
            fields: {
                'Question': question || '',
                'Caption': caption || '',
                'Timestamp': createdAt || new Date().toISOString(),
                'Created At': createdAt || new Date().toISOString(),
                'Source': autoGenerated ? 'batch-processing' : 'memory-drawer-app',
                'Filename': filename || '',
                'Status': '발행 전',
                'Image': dropboxUrl || ''
            }
        };

        const tableNameOrId = process.env.AIRTABLE_TABLE_ID;
        const apiUrl = `https://api.airtable.com/v0/${process.env.AIRTABLE_BASE_ID}/${encodeURIComponent(tableNameOrId)}`;

        const response = await fetch(apiUrl, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${process.env.AIRTABLE_API_TOKEN}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(recordData),
        });

        if (!response.ok) {
            const errorData = await response.text();
            throw new Error(`Airtable API 오류: ${response.status} - ${errorData}`);
        }

        const result = await response.json();

        return res.status(200).json({
            success: true,
            message: '저장 완료',
            airtableResponse: result
        });

    } catch (error: any) {
        console.error('❌ 서버 오류:', error);
        return res.status(500).json({
            success: false,
            error: error.message
        });
    }
}
